import { TrainingCategoryEnum } from '../enums/training-category.enum';
import { TrainingItem } from '../interfaces/training-item.interface';

export const TRAININGS_CATEGORY: TrainingItem[] = [
  {
    category: TrainingCategoryEnum.NR05,
    nr: 'NR-05',
    title: 'CIPA — Formação de Cipeiros',
    description: 'Capacitação completa para membros titulares, suplentes e designado da CIPA. Prevenção de acidentes, doenças, assédio sexual e violência no trabalho.',
    duration: '20h',
    recurrence: 'A cada mandato',
    color: 'var(--purple)',
    tagIcon: 'fas fa-sync',
    link: '#nr05d'
  },
  {
    category: TrainingCategoryEnum.NR05,
    nr: 'NR-05',
    title: 'Designado de CIPA',
    description: 'Treinamento para o designado de CIPA em empresas dispensadas de constituir a Comissão (até 19 empregados conforme quadro).',
    duration: '8h',
    recurrence: 'Designado',
    color: 'var(--purple)',
    tagIcon: 'fas fa-user',
    link: '#nr05d'
  },
  {
    category: TrainingCategoryEnum.NR06,
    nr: 'NR-06',
    title: 'EPI — Uso, Guarda e Conservação',
    description: 'Treinamento sobre uso correto, guarda, conservação, higienização, limitações e descarte de Equipamentos de Proteção Individual. Verificação do CA.',
    duration: '4h',
    recurrence: 'Todos',
    color: 'var(--green)',
    tagIcon: 'fas fa-users',
    link: '#nr06d'
  },
  {
    category: TrainingCategoryEnum.NR10,
    nr: 'NR-10',
    title: 'Básico — Segurança em Eletricidade',
    description: 'Curso obrigatório para todos que interajam com instalações elétricas. Riscos elétricos, medidas de controle, EPIs, procedimentos de desenergização e primeiros socorros.',
    duration: 'Recicl. 8h / 2 anos',
    recurrence: '',
    color: 'var(--amber)',
    tagIcon: '',
    link: '#nr10d'
  },
  {
    category: TrainingCategoryEnum.NR10,
    nr: 'NR-10',
    title: 'SEP — Sistema Elétrico de Potência',
    description: 'Curso Complementar obrigatório para trabalhos em alta tensão (>1kV CA / >1,5kV CC). Linhas de transmissão, subestações, trabalho sob tensão.',
    duration: 'Recicl. 8h / 2 anos',
    recurrence: '',
    color: 'var(--amber)',
    tagIcon: '',
    link: '#nr10d'
  },
  {
    category: TrainingCategoryEnum.NR10,
    nr: 'NR-10',
    title: 'Reciclagem Básico NR-10',
    description: 'Reciclagem obrigatória a cada 2 anos para trabalhadores com curso básico NR-10, ou após afastamento, mudança de função ou alterações nas instalações.',
    duration: '8h',
    recurrence: 'Bienal',
    color: 'var(--amber)',
    tagIcon: 'fas fa-sync',
    link: '#nr10d'
  },
  {
    category: TrainingCategoryEnum.NR10,
    nr: 'NR-10',
    title: 'Reciclagem SEP',
    description: 'Reciclagem bienal obrigatória do curso complementar SEP para trabalhadores que atuam em alta tensão.',
    duration: '8h',
    recurrence: 'Bienal',
    color: 'var(--amber)',
    tagIcon: 'fas fa-sync',
    link: '#nr10d'
  },
  {
    category: TrainingCategoryEnum.NR11,
    nr: 'NR-11',
    title: 'Operador de Empilhadeira',
    description: 'Empilhadeira a combustão, elétrica e retrátil. Inspeção pré-uso, estabilidade, capacidade de carga, manobras seguras e sinalização.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--blue)',
    tagIcon: '',
    link: '#nr11d'
  },
  {
    category: TrainingCategoryEnum.NR11,
    nr: 'NR-11',
    title: 'Operador de PTA — Plataforma Elevatória',
    description: 'Plataformas articuladas, telescópicas e tesoura. Limites de carga, inspeção, posicionamento, condições climáticas e resgate.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--blue)',
    tagIcon: '',
    link: '#nr11d'
  },
  {
    category: TrainingCategoryEnum.NR11,
    nr: 'NR-11',
    title: 'Operador de Ponte Rolante',
    description: 'Ponte rolante, pórtico e talha. Sinalização, capacidade nominal, inspeção de cabos, ganchos e movimentação segura de cargas suspensas.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--blue)',
    tagIcon: '',
    link: '#nr11d'
  },
  {
    category: TrainingCategoryEnum.NR11,
    nr: 'NR-11',
    title: 'Operador de Retroescavadeira',
    description: 'Retroescavadeira e pá carregadeira. Inspeção, operação, limitações do equipamento, sinalização de área e transporte.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--blue)',
    tagIcon: '',
    link: '#nr11d'
  },
  {
    category: TrainingCategoryEnum.NR11,
    nr: 'NR-11',
    title: 'Operador de Guindaste / Munck',
    description: 'Guindaste e caminhão munck. Plano de rigging, tabela de carga, raio de operação, ângulos, sinalização e isolamento de área.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--blue)',
    tagIcon: '',
    link: '#nr11d'
  },
  {
    category: TrainingCategoryEnum.NR11,
    nr: 'NR-11',
    title: 'Operador de Pá Carregadeira',
    description: 'Operação segura de pá carregadeira (minicarregadeira / bob cat). Inspeção, manobras, sinalização e limitações.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--blue)',
    tagIcon: '',
    link: '#nr11d'
  },
  {
    category: TrainingCategoryEnum.NR11,
    nr: 'NR-11',
    title: 'Sinaleiro / Rigger',
    description: 'Sinais convencionais de guindaste, amarração e lingamento de cargas, escolha de acessórios (cintas, cabos, manilhas) e ângulos.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--blue)',
    tagIcon: '',
    link: '#nr11d'
  },
  {
    category: TrainingCategoryEnum.NR12,
    nr: 'NR-12',
    title: 'Segurança em Máquinas e Equipamentos',
    description: 'Capacitação obrigatória: riscos, proteções (fixas, móveis, intertravamento), parada de emergência, procedimentos seguros e LOTO.',
    duration: '4h+',
    recurrence: 'Conforme necessidade',
    color: 'var(--indigo)',
    tagIcon: 'fas fa-sync',
    link: '#nr12d'
  },
  {
    category: TrainingCategoryEnum.NR12,
    nr: 'NR-12',
    title: 'LOTO — Bloqueio e Etiquetagem de Energias',
    description: 'Procedimentos de Lockout/Tagout para bloqueio de energias (elétrica, pneumática, hidráulica, mecânica) durante manutenção e intervenções.',
    duration: '4h',
    recurrence: 'Lockout/Tagout',
    color: 'var(--indigo)',
    tagIcon: 'fas fa-lock',
    link: '#nr12d'
  },
  {
    category: TrainingCategoryEnum.NR13,
    nr: 'NR-13',
    title: 'Operador de Caldeiras',
    description: 'Treinamento de Segurança na Operação de Caldeiras: grandezas físicas, tipos de caldeiras, operação, tratamento de água, prevenção contra explosões.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--fire)',
    tagIcon: '',
    link: '#nr13d'
  },
  {
    category: TrainingCategoryEnum.NR13,
    nr: 'NR-13',
    title: 'Unidades de Processo (Vasos de Pressão)',
    description: 'Vasos de pressão, tubulações industriais e tanques metálicos. Classificação, dispositivos de segurança, procedimentos operacionais e emergência.',
    duration: 'Recicl. 8h',
    recurrence: '',
    color: 'var(--fire)',
    tagIcon: '',
    link: '#nr13d'
  },
  {
    category: TrainingCategoryEnum.NR13,
    nr: 'NR-13',
    title: 'Reciclagem — Operador de Caldeiras',
    description: 'Reciclagem obrigatória para operadores de caldeiras conforme periodicidade da NR-13.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--fire)',
    tagIcon: 'fas fa-sync',
    link: '#nr13d'
  },
  {
    category: TrainingCategoryEnum.NR13,
    nr: 'NR-13',
    title: 'Reciclagem — Unidades de Processo',
    description: 'Reciclagem obrigatória para operadores de vasos de pressão e trabalhadores de unidades de processo.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--fire)',
    tagIcon: 'fas fa-sync',
    link: '#nr13d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Admissional / Integração — Construção Civil',
    description: 'Treinamento admissional obrigatório: riscos da obra, condições ambientais, medidas de proteção coletiva e individual, normas internas.',
    duration: '8h',
    recurrence: 'A cada obra',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Escavações, Fundações e Desmonte de Rochas',
    description: 'Riscos de soterramento, escoramento de valas, sinalização, condições do solo, taludes e SPT.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Montagem e Desmontagem de Andaimes',
    description: 'Andaimes fachadeiro, tubular, multidirecional. Montagem, desmontagem, inspeção, travamento, guarda-corpo e acesso seguro.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Demolição',
    description: 'Planejamento e sequência de demolição, isolamento de área, proteções, remoção de materiais e gestão de resíduos.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Montagem de Estruturas Metálicas',
    description: 'Montagem/desmontagem, içamento de peças, soldagem em altura, proteção contra quedas e plano de rigging.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Operação de Gruas',
    description: 'Operação segura de gruas (torre fixa, ascensional, móvel). Plano de carga, condições climáticas, sinalização e manutenção.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Carpintaria e Armações de Aço',
    description: 'Serra circular, bancadas, armação de ferragens, riscos com ferramentas cortantes e medidas de proteção específicas.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR18,
    nr: 'NR-18',
    title: 'Instalações Elétricas Provisórias',
    description: 'Instalações elétricas em canteiros de obras, quadros de distribuição, aterramento e proteção contra choques.',
    duration: '8h',
    recurrence: 'Periódica',
    color: 'var(--ember)',
    tagIcon: 'fas fa-sync',
    link: '#nr18d'
  },
  {
    category: TrainingCategoryEnum.NR20,
    nr: 'NR-20',
    title: 'Iniciação — Inflamáveis e Combustíveis',
    description: 'Trabalhadores que adentram a área ou realizam atividades de apoio em instalações Classe I, II ou III. Noções básicas de segurança.',
    duration: 'Recicl. 2h / 3 anos',
    recurrence: '',
    color: 'rgb(161, 98, 7)',
    tagIcon: '',
    link: '#nr20d'
  },
  {
    category: TrainingCategoryEnum.NR20,
    nr: 'NR-20',
    title: 'Básico — Inflamáveis (Classe I)',
    description: 'Atuação direta em instalações Classe I (postos de combustíveis). Propriedades dos inflamáveis, riscos, medidas de controle e emergência.',
    duration: 'Recicl. 4h / 3 anos',
    recurrence: '',
    color: 'var(--amber)',
    tagIcon: '',
    link: '#nr20d'
  },
  {
    category: TrainingCategoryEnum.NR20,
    nr: 'NR-20',
    title: 'Intermediário — Inflamáveis (Classe II)',
    description: 'Atuação direta em instalações Classe II (engarrafadoras de GLP, industriais). Análise de risco, controle de fontes de ignição, plano de emergência.',
    duration: 'Recicl. 8h / 3 anos',
    recurrence: '',
    color: 'var(--ember)',
    tagIcon: '',
    link: '#nr20d'
  },
  {
    category: TrainingCategoryEnum.NR20,
    nr: 'NR-20',
    title: 'Avançado I — Inflamáveis (Classe III)',
    description: 'Trabalhadores que adentram a área em instalações Classe III (refinarias, terminais, petroquímicas).',
    duration: 'Recicl. 8h / 3 anos',
    recurrence: '',
    color: 'var(--fire)',
    tagIcon: '',
    link: '#nr20d'
  },
  {
    category: TrainingCategoryEnum.NR20,
    nr: 'NR-20',
    title: 'Avançado II — Inflamáveis (Classe III)',
    description: 'Operação, manutenção, inspeção e atendimento a emergências em instalações Classe III. Nível mais completo.',
    duration: 'Recicl. 8h / 3 anos',
    recurrence: '',
    color: 'var(--fire)',
    tagIcon: '',
    link: '#nr20d'
  },
  {
    category: TrainingCategoryEnum.NR23,
    nr: 'NR-23',
    title: 'Brigada de Incêndio e Emergência',
    description: 'Formação de brigadistas: teoria do fogo, classes de incêndio, extintores, hidrantes, evacuação, primeiros socorros e simulados práticos. Conforme NBR 14276.',
    duration: '8h+',
    recurrence: 'Recicl. anual',
    color: 'var(--rose)',
    tagIcon: 'fas fa-sync',
    link: '#nr23d'
  },
  {
    category: TrainingCategoryEnum.NR23,
    nr: 'NR-23',
    title: 'Noções de Combate a Incêndio e Evacuação',
    description: 'Treinamento básico para todos os trabalhadores: uso de extintores, rotas de fuga, ponto de encontro e procedimentos de evacuação.',
    duration: '4h',
    recurrence: 'Todos',
    color: 'var(--rose)',
    tagIcon: 'fas fa-users',
    link: '#nr23d'
  },
  {
    category: TrainingCategoryEnum.NR33,
    nr: 'NR-33',
    title: 'Espaços Confinados — Trabalhadores Autorizados e Vigias',
    description: 'Reconhecimento de espaços confinados, riscos atmosféricos, monitoramento, comunicação, equipamentos de resgate e procedimentos de emergência.',
    duration: 'Recicl. 8h / anual',
    recurrence: '',
    color: 'var(--purple)',
    tagIcon: '',
    link: '#nr33d'
  },
  {
    category: TrainingCategoryEnum.NR33,
    nr: 'NR-33',
    title: 'Espaços Confinados — Supervisor de Entrada',
    description: 'Conteúdo dos trabalhadores + gestão de PET, avaliação de riscos, calibração de detectores, planejamento de resgate e coordenação de equipes.',
    duration: 'Recicl. 8h / anual',
    recurrence: '',
    color: 'var(--purple)',
    tagIcon: '',
    link: '#nr33d'
  },
  {
    category: TrainingCategoryEnum.NR33,
    nr: 'NR-33',
    title: 'Reciclagem — Vigias e Trabalhadores',
    description: 'Reciclagem anual obrigatória para vigias e trabalhadores autorizados de espaços confinados.',
    duration: '8h',
    recurrence: 'Anual',
    color: 'var(--purple)',
    tagIcon: 'fas fa-sync',
    link: '#nr33d'
  },
  {
    category: TrainingCategoryEnum.NR33,
    nr: 'NR-33',
    title: 'Reciclagem — Supervisor de Entrada',
    description: 'Reciclagem anual obrigatória para Supervisores de Entrada em Espaços Confinados.',
    duration: '8h',
    recurrence: 'Anual',
    color: 'var(--purple)',
    tagIcon: 'fas fa-sync',
    link: '#nr33d'
  },
  {
    category: TrainingCategoryEnum.NR35,
    nr: 'NR-35',
    title: 'Trabalho em Altura — Formação',
    description: 'Formação completa: análise de risco, sistemas de proteção, EPI (cinto, talabarte, trava-queda), ancoragem, resgate e simulado prático.',
    duration: 'Recicl. 8h / 2 anos',
    recurrence: '',
    color: 'var(--cyan)',
    tagIcon: '',
    link: '#nr35d'
  },
  {
    category: TrainingCategoryEnum.NR35,
    nr: 'NR-35',
    title: 'Trabalho em Altura — Reciclagem',
    description: 'Reciclagem bienal obrigatória ou após afastamento superior a 90 dias, mudança de procedimentos ou acidente/incidente grave.',
    duration: '8h',
    recurrence: 'Bienal',
    color: 'var(--cyan)',
    tagIcon: 'fas fa-sync',
    link: '#nr35d'
  },
  {
    category: TrainingCategoryEnum.OUTROS,
    nr: 'NR-07',
    title: 'Primeiros Socorros',
    description: 'Noções de primeiros socorros conforme NR-07/PCMSO: RCP, queimaduras, fraturas, hemorragias, desmaios, engasgamento e uso de DEA.',
    duration: '8h',
    recurrence: 'NR-07',
    color: 'var(--teal)',
    tagIcon: 'fas fa-heartbeat',
    link: '#orcamento'
  },
  {
    category: TrainingCategoryEnum.OUTROS,
    nr: 'NR-17',
    title: 'Ergonomia no Trabalho',
    description: 'Capacitação em ergonomia: postura, movimentação manual de cargas, organização do trabalho, pausas e ginástica laboral.',
    duration: '4h',
    recurrence: 'Ergonomia',
    color: 'var(--sky)',
    tagIcon: 'fas fa-chair',
    link: '#orcamento'
  }
]
