export enum FaqTypeEnum {
  EQUIPAMENTOS = 'EQUIPAMENTOS',
  INSPECAO = 'INSPECAO',
  TESTES = 'TESTES',
  PROFISSIONAL = 'PROFISSIONAL',
  SEGURANCA = 'SEGURANCA',
  SOLDAGEM = 'SOLDAGEM',
  DOCUMENTACAO = 'DOCUMENTACAO'
}
